import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

import Header from "@/components/header"
import Sidebar from "@/components/sidebar"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Movie App",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="h-full">
            <body
                className={`${geistSans.variable} ${geistMono.variable} h-full overflow-hidden antialiased`}>
                <div className="flex h-full min-h-0 flex-col">
                    <Header />

                    <main className="flex min-h-0 flex-1 flex-row overflow-hidden">
                        <Sidebar />
                        <section className="min-h-0 min-w-0 flex-1 overflow-y-auto p-4">
                            {children}
                        </section>
                    </main>
                </div>
            </body>
        </html>
    )
}
